### ISSUE TITLE
Graph issues

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#1]
Since moving the graph from the only element to one of two (with the spectral plots), the following are broken:

1. the tooltips are no longer in the right place
2. Click and drag doesn't work to move the whole graph
3. the search box is now *under* the graph, not above

**Comment by joewandy** [comment]
Search box is now in the right place. Also split the long graph.html into:
- basicviz-spectra.js for the spectra plotting JS
- basicviz-network.js for the network graph JS
- basicviz.css for the CSS
- graph.html is now just a short HTML that calls the above

Still broken:
1. Tooltip position is wrong
2. Search box is broken and the reset button there doesn't work
3. Cannot drag the network

**Comment by laurabzz** [comment]
1. Tooltip position is still wrong - scrolling the page messes it up. I'll look into it if I have a spare minute. Quick browsing didn't bring any solutions. If page is not scrolled, tooltip position is correct.
2. Search box - autocomplete works (since "autocompleteFix" branch). But the searchNode() and resetSearch() methods are inside the plot_graph() method so they cannot be called in the inline html.
3. I've put different graphs in different svgs and divs ("svg_fixes" branch). That allows dragging the whole network graph and zooming is done anywhere on that svg.
