### ISSUE TITLE
Export MS1-PLAGE results from ms2lda.org

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#107]
User request:

Also, is there a way I can extract the 5-10 Mass2Motifs with the highest PLAGE score, listing corresponding metabolites and annotation (if present)? Our dataset is quite large, so it always takes a while until the corresponding visualization has been loaded, which also doesn't make trends obvious all the time only by visual inspection. I'd like for example to find discriminative ions between bioactive/non-bioactive sample groups and Mass2Motifs that are associated with those.

Justin: perhaps create a csv Table to export?

**Comment by sdrogers** [comment]
Should be straightforward -- needs two things I think.
1. A new menu item for viewing the ms1 analysis results (don't seem to have this anywhere at the moment?)
2. Button on the table in 1 (there by default if we use data tables)

**Comment by justinjjvanderhooft** [comment]
Sounds like a plan!

**Comment by ymcdull** [comment]
Hi Justin,
Have a demo here:
http://52.51.126.142:8000/ms1analysis/show_ms1analysis/150/

This page list all the ms1 analysis results, and when you click one ms1 analysis, it will list all molecule results and Mass2Motif results in two tables.

Since we have links for names in the table, users can just use them to link to molecules or Mass2Motifs.

Can you have a look, and check if some information is missing? or any suggestions?

If everything is fine, I will make a pull request soon.

Thank.

**Comment by justinjjvanderhooft** [comment]
Hi Frank,

Looks fine to me - the links to the Mass2Motifs and Molecules work - and the CSVs download okay. 

Many thanks!

Justin

**Comment by justinjjvanderhooft** [comment]
A nice addition to the website :-)

**Comment by sdrogers** [comment]
FrAnK — will you be adding this as a new option on the main menu for each experiment? If so, I guess it should only appear if they have setup some MS1 analyses….
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by justinjjvanderhooft** [comment]
Good point!

**Comment by ymcdull** [comment]
Hi Simon,
The new option was already there in main menu, and just added the "if else" for I guess it should only appear if they have setup some MS1 analyses.
And a pull request submitted.

Frank
